In [20]:
import pandas as pd
import numpy as np
import matplotlib as plt
import yfinance as yf

In [2]:
#Seleccionamos los tickers
ticker = ["AMZN", "MSFT"]

In [10]:
#Descargamos la data en este caso de 2 años
datos = yf.download(ticker, period= "2y") 
datos.head(5)

[*********************100%***********************]  2 of 2 completed

Price            Close                    High                     Low  \
Ticker            AMZN        MSFT        AMZN        MSFT        AMZN
Date
2024-07-17  187.929993  436.657593  191.580002  437.967031  185.990005
2024-07-18  183.750000  433.556335  189.679993  437.770112  181.449997
2024-07-19  183.130005  430.346771  184.929993  434.314446  180.110001
2024-07-22  182.550003  436.086548  185.059998  437.720867  182.479996
2024-07-23  186.410004  437.967041  189.389999  441.452277  183.559998

Price                         Open                Volume
Ticker            MSFT        AMZN        MSFT      AMZN      MSFT
Date
2024-07-17  432.384747  191.350006  435.741989  48076100  21778000
2024-07-18  427.678706  189.589996  437.464911  51043600  20794800
2024-07-19  425.315850  181.139999  426.398837  43081800  20940400
2024-07-22  432.118904  185.000000  434.954347  39931900  15808800
2024-07-23  436.244118  184.100006  437.031728  47537700  13107100

In [11]:
#Solo usamos los precios de cierre y lo ponemos en una nueva variable
precio = datos["Close"]
precio

Ticker            AMZN        MSFT
Date
2024-07-17  187.929993  436.657593
2024-07-18  183.750000  433.556335
2024-07-19  183.130005  430.346771
2024-07-22  182.550003  436.086548
2024-07-23  186.410004  437.967041
...                ...         ...
2026-07-10  245.339996  385.100006
2026-07-13  247.309998  390.989990
2026-07-14  247.490005  384.929993
2026-07-15  254.960007  395.630005
2026-07-16  249.889999  401.100006

[501 rows x 2 columns]

In [14]:
#Hallamos los retornos y borramos la primera fila
returns = precio.pct_change().dropna()
returns

Ticker          AMZN      MSFT
Date
2024-07-18 -0.022242 -0.007102
2024-07-19 -0.003374 -0.007403
2024-07-22 -0.003167  0.013338
2024-07-23  0.021145  0.004312
2024-07-24 -0.029934 -0.035855
...              ...       ...
2026-07-10 -0.006881  0.001925
2026-07-13  0.008030  0.015295
2026-07-14  0.000728 -0.015499
2026-07-15  0.030183  0.027797
2026-07-16 -0.019886  0.013826

[500 rows x 2 columns]

In [26]:
#Hallamos el retorno compuesto diario
r_days = returns.shape[0]
returns_day = (returns+1).prod()**(1/r_days) -1
returns_day

Ticker
AMZN    0.00057
MSFT   -0.00017
dtype: float64

In [27]:
#Hallamos el retorno compuesto anual
returns_all = (returns_day+1)**252 -1
returns_all

Ticker
AMZN    0.154440
MSFT   -0.041906
dtype: float64

In [28]:
#Ahora hallamos la volatilidad anualizada
volatilidad = returns.std()*(252**0.5)
volatilidad

Ticker
AMZN    0.328514
MSFT    0.263675
dtype: float64

In [ ]:
#RATIOS

In [29]:
r =returns_all/volatilidad
r

Ticker
AMZN    0.470118
MSFT   -0.158929
dtype: float64

In [30]:
riskfree = 0.03
rs =(returns_all-riskfree)/volatilidad
rs

Ticker
AMZN    0.378797
MSFT   -0.272706
dtype: float64