In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import yfinance as yf

In [2]:
#Seleccionamos los tickers
ticker = ["AMZN", "MSFT"]

In [3]:
#Descargamos la data en este caso de 2 años
datos = yf.download(ticker, period= "2y") 
datos.head(5)

[*********************100%***********************]  2 of 2 completed

Price            Close                    High                     Low  \
Ticker            AMZN        MSFT        AMZN        MSFT        AMZN
Date
2024-07-25  179.850006  411.926270  183.899994  423.149876  176.800003
2024-07-26  182.500000  418.689941  183.190002  422.283490  180.240005
2024-07-29  183.199997  420.127380  184.750000  425.463502  182.380005
2024-07-30  181.710007  416.376343  185.860001  422.411471  179.380005
2024-07-31  186.979996  411.877075  187.940002  415.253997  184.460007

Price                         Open                Volume
Ticker            MSFT        AMZN        MSFT      AMZN      MSFT
Date
2024-07-25  411.050056  182.910004  422.165349  44464200  29943800
2024-07-26  410.813722  180.389999  411.729356  29506000  23583800
2024-07-29  418.128791  183.839996  424.902314  33270100  15125800
2024-07-30  410.902343  184.720001  421.102062  39508600  32687600
2024-07-31  405.832062  185.050003  413.993803  41667300  42891400

In [4]:
#Solo usamos los precios de cierre y lo ponemos en una nueva variable
precio = datos["Close"]
precio

Ticker            AMZN        MSFT
Date
2024-07-25  179.850006  411.926270
2024-07-26  182.500000  418.689941
2024-07-29  183.199997  420.127380
2024-07-30  181.710007  416.376343
2024-07-31  186.979996  411.877075
...                ...         ...
2026-07-20  249.990005  402.290009
2026-07-21  247.550003  397.750000
2026-07-22  244.850006  390.339996
2026-07-23  233.660004  381.579987
2026-07-24  232.110001  381.700012

[501 rows x 2 columns]

In [5]:
#Hallamos los retornos y borramos la primera fila
returns = precio.pct_change().dropna()
returns

Ticker          AMZN      MSFT
Date
2024-07-26  0.014734  0.016420
2024-07-29  0.003836  0.003433
2024-07-30 -0.008133 -0.008928
2024-07-31  0.029002 -0.010806
2024-08-01 -0.015563 -0.002964
...              ...       ...
2026-07-20  0.011164  0.021507
2026-07-21 -0.009760 -0.011285
2026-07-22 -0.010907 -0.018630
2026-07-23 -0.045701 -0.022442
2026-07-24 -0.006634  0.000315

[500 rows x 2 columns]

In [7]:
#Hallamos el retorno compuesto diario
r_days = returns.shape[0]
returns_day = (((returns+1).prod())**(252/r_days)) -1
returns_day

Ticker
AMZN    0.137195
MSFT   -0.037681
dtype: float64

In [28]:
#Ahora hallamos la volatilidad anualizada
volatilidad = returns.std()*(252**0.5)
volatilidad

Ticker
AMZN    0.328514
MSFT    0.263675
dtype: float64

In [ ]:
#RATIOS

In [29]:
r =returns_all/volatilidad
r

Ticker
AMZN    0.470118
MSFT   -0.158929
dtype: float64

In [30]:
riskfree = 0.03
rs =(returns_all-riskfree)/volatilidad
rs

Ticker
AMZN    0.378797
MSFT   -0.272706
dtype: float64