In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import yfinance as yf

In [46]:
#Extraemos data del ticker AMZN
#Puedes cambiar la fecha, el ticker para prácticar. Esto es con un solo ticker.
tickers = "AMZN"
data = yf.download(tickers, start= "2025-01-01", end = "2025-08-31")
data.head(5)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AMZN        AMZN        AMZN        AMZN      AMZN
Date
2025-01-02  220.220001  225.149994  218.190002  222.029999  33956600
2025-01-03  224.190002  225.360001  221.619995  222.509995  27515600
2025-01-06  227.610001  228.839996  224.839996  226.779999  31849800
2025-01-07  222.110001  228.380005  221.460007  227.899994  28084200
2025-01-08  222.130005  223.520004  220.199997  223.190002  25033300

In [47]:
#Solo nos quedamos con los precios de cierre
precios = data["Close"]
precios.head(5)

Ticker            AMZN
Date
2025-01-02  220.220001
2025-01-03  224.190002
2025-01-06  227.610001
2025-01-07  222.110001
2025-01-08  222.130005

In [48]:
#obtenemos la rentabilidades
returns = precios.pct_change().dropna()
returns

Ticker          AMZN
Date
2025-01-03  0.018027
2025-01-06  0.015255
2025-01-07 -0.024164
2025-01-08  0.000090
2025-01-10 -0.014361
...              ...
2025-08-25 -0.003933
2025-08-26  0.003378
2025-08-27  0.001793
2025-08-28  0.010824
2025-08-29 -0.011226

[164 rows x 1 columns]

In [49]:
#obtenemos la rentabilidad anualizada
nday = returns.shape[0]
returns_anu = ((((1+returns).prod())**(252/nday))-1)*100
returns_anu

Ticker
AMZN    6.191378
dtype: float64

In [50]:
#Primera manera de usar condicionales
re = returns_anu["AMZN"]
if re > 4:
    print("invertir")
if re < 4: 
    print("no invertir")

invertir

In [51]:
#Segunda manera 
re = returns_anu["AMZN"]
if re > 4:
    print("invertir en su totalidad")
elif re > 2:
    print("invertir solo el 30")
else:
    print("no invertir")

invertir en su totalidad

In [52]:
#Tercera manera
re = returns_anu["AMZN"]
if re > 4:
    print("invertir")
else:
    print("no invertir")

invertir